
Certificate Signing Request - This takes care of creating public certificates through controller manager. 

We need to paste the csr file content in base64 encode format to the manifest, then the admin can approve it using kubectl command

```
k certificate approve <name>
```


```

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: RVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXNhV0ZhYlJEdFBUYXpLdmhyYjRwenBJQytiZ1NiK3B3bFJXNGVGN09NbUxZCjlYbTRjMDR3Z3RvYXhTa1FkT3B2NmFsejFCVzdjcjRlejdRRFdraklFbnRPZitvT25ncjF1RWNtSmM3MkZwQUIKb0NVd0U4Nzg4YVdUL3RsbUhWRDQ5YkFlRnhKWWVUa01temVjRlIzMklCT0hvWTRsMURwbXVEUUxyVmZpM3pDTAo1NWdMcmRyRUxEKzJ0T0trVlAvSk5Hb3J2enhIbk9CSEJZZnVaK2hBaFdJNDBaalJRSXBYNnZuMWk2eE5GNUJTCnhLNFR3cjArMytlRDZsR1Fub0tKT29YeFpDMHBvay9aNlIrVEtnS00wN2hhcnF2U1dCTTZ4ZXp1cFUwSHVZWisKRHJPUnBjK1pPVWd5T241SmdwVEJabnhpU2hrS1hycHFIVmtTV01MWHpRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBR1pqOCtiemVuaTZoSTVldW92ZlFKWkZ6bVVac0hocTZBZkMvZjUySXZuVlJMMkFyQ0FwCitmK25KQW5TbExNYkRuWkFJV3I3K1hqcUlsbzMxTUwxNUZQTFZ6blprdkN6cTQ5RmJpY2pmWWZPMTIyWlp1b0kKSkV6SExoc2dRRGVXM21uRkI2ekhMTjBNREZRTU5ZNTlYVUJEUGM2a1I3TE01V0RXY3Qxa043SmUxRWlHU3FJdQpHTW5wQktHbEZKWUx1TFNKUWViUmd6di8wOVhna1owRmgyWVJlZTJiMmoxU3BkRFpMS3Z4eS9PdVEyVXN3SGlwCkhQMWFFcGQ5OXN6V010SFJ6Snc4eHErU3BHVjFxaEM0dFhwaVZYRFVZOEZDWEoxUUN5b1RXQ291ZmhyL3V4c0IKUmUwTGkyV1ZlWmYvbjcwbUx6RWlGZ1dmalZ0enlTYm9uKzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth

```  
